# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_dialect_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialect',
            options={'ordering': ['index', 'language', 'name']},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['gloss__region__dialect__index', 'index']},
        ),
        migrations.AlterField(
            model_name='dialect',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
